import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const user = useUser();
  const { isSignedIn } = user;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello from Clerk</h1>
        {!isSignedIn && <SignInButton />}
        {isSignedIn && <h1>{`Your signed in as ${user.user.fullName}`}</h1>}
        {isSignedIn && <SignOutButton />}
      </main>
    </>
  );
}
